// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPublicIP():Promise<string>;

export function GetVersion():Promise<string>;

export function Trace(arg1:string,arg2:number,arg3:number):Promise<string>;
